server:
  port: 80


spring:
  autoconfigure:
    exclude:
      # 排除 MongoDB 自动配置 如有需要,需要自行开启
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration

  cloud:
    gateway:
      routes:
        - id: v2
          uri: https://api-xfb.easipay.net/v1
          predicates:
            - Path=/v2/**
          filters:
            - "MessageService"
            - RewritePath=/v2(?<segment>/?.*), /v1$\{segment}
        - id: v1
          uri: https://api-xfb.easipay.net/v1
          predicates:
            - Path=/v1/**
          filters:
            - "Sign"

logging:
  level:
    org:
      springframework: error
    tech:
      aomi: debug
  pattern:
    console: "%clr(%d){blue} [%clr(%-5level){lightgreen}] [%logger{0}] - %msg%n"
    file: "%d [%-5level] [%logger{0}] - %msg%n"

gateway:
  publicKey: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAylGKjhqXjh8tKD2yTqBXnBzQBJShyFJhfo9lnl3OySLM4zAJ64gZHA8dLw6tJFtxL3aVE605PGN/TB9ghtWUMCkLFva+6IoyokiAIMkJcSpspXOLzNuIPVotQb5JJ7DeL2pqIR/INKcDgUmmVfh3iR0dLCVOznmew1ooUnaf+p55emFnS5ebKWKuhps1H2eldGWwKNoQweqJuk8G1WxnfZqRgCTW/mQ9umKX2kkv92hPWoTppeaRFwqAe2OMP/O0RrmMwV7l24LcvSjNazCY2JK36dW7ALX/2h7oWR7L6i93UxQgwb0Zze7Rm880XHYz/U9DGoGcbXhRy7kLh10KQQIDAQAB"
  privateKey: "MIIEwAIBADANBgkqhkiG9w0BAQEFAASCBKowggSmAgEAAoIBAQDKUYqOGpeOHy0oPbJOoFecHNAElKHIUmF+j2WeXc7JIszjMAnriBkcDx0vDq0kW3EvdpUTrTk8Y39MH2CG1ZQwKQsW9r7oijKiSIAgyQlxKmylc4vM24g9Wi1BvkknsN4vamohH8g0pwOBSaZV+HeJHR0sJU7OeZ7DWihSdp/6nnl6YWdLl5spYq6GmzUfZ6V0ZbAo2hDB6om6TwbVbGd9mpGAJNb+ZD26YpfaSS/3aE9ahOml5pEXCoB7Y4w/87RGuYzBXuXbgty9KM1rMJjYkrfp1bsAtf/aHuhZHsvqL3dTFCDBvRnN7tGbzzRcdjP9T0MagZxteFHLuQuHXQpBAgMBAAECggEBAMRw0fhSR48+JClrZkLDmu1AaJXZ/w+zNWieMQvIh6xx9sAsd6VSmxbMcgir1l9zzf1IxUy6p9VDwmkWGjIxFFaCs3rTj9/Xt3wsqwOqT1mq2Jz5COeazLjNYx3vdbZtG/6r82pAIrNE6rlQ2omk2+Os+hNQEimWmxmQ44/WEFVUaFrTw4yJR+B3lE1ZqpobCr4pEJT01Ds9pDAI/Cl7uGMwfd7bmUJ+sU9wFEjZtZE/UNcQQgqTxb4WgCU7ZDRFrvZIqCx5buACLZR0FtQGEksXg43/x2PMEhLvlcv0XShoi6fIKFdeTgDGbnd+YFrK9TpVOmxVN0tkTBRwZrslVcECgYEA+SPP4GaX6QS6bTKVfMb21XkqzoKvxlQFW56NDP034iiQzc3jGaRm6pvZbQDecEVgcd8C22vJMKZbmBTl3/hjKkjVMdgyKlwi7vKBAcoZVmvPfxFLkkT91uMKWO14EtuWHG/6Mpz8JAN4VAUVQsS0L9Ubkpjx56Ew/Fkn56ZdYRkCgYEAz+Ovaa2DaNX44vBxhcCUSuCWA1ea5U0UXnaHkHAwbQVo9kwNhxyzyauq5NYJol4Pyk6WBpJfpLhjsxmLI/SFVn4ZyaY6eUvRoWpFpskYvynbDl9LiuC1q5YOq+nrLtlyi1HNAz8ZJfmQLlGJyL7zCYnqmnUZbfMCqHf53jaVz2kCgYEAsHKDlEs0xWx62EGeC7wiLvhcr9twwAbbsJKvFQb1oC/YtlldwNhlpzzvlTqrT1pjPuKR9HL3D4SSlDggwin5mYXxsBaNGOEeQJrxcSIAJeu/DiBipFpGaP1tY6PziW+JdeR8j4INNThb7S2YbCxB7SqCF6ZIlSLdPaurDm4N7mkCgYEAi2AY4H7mFUkvXebaFVQxl6nOqVr4jDcLKvHInXu5272+yzHd9/G0T8b6AgXF28e4Smg5iRplaSf+H7tGX8q2AnD0lQ8PMPc2CkQXgmRcZP2I0a/uE6Pn6KvoFjXz6Sr78o/bJQwOrjkNAyDDgYUTqBeA5CER9XbxF0WojeSGt9ECgYEAzl8d3PKMOly74bqd0eoQNnLUWrgAYV2w9kNCtWkETtRz82j0CVSkbFTOsMTuhGW0gj0AUTGCZjDyNGEOTnLYggIRUOTSkGjlv21+rM5xtYRAg5slec2VuNYdnlByquKwXXiHpH5mNstkiE9jWVdH+aNwq5GEOQ5OrmD/O/CQtlE="
