server:
  port: 80


spring:
  cloud:
    gateway:
      routes:
        - id: transform
          uri: https://top.com
          predicates:
            - Path=/transform/**
          filters:
            - "Transform"
        - id: v2
          uri: https://api-xfb.easipay.net/v1
          predicates:
            - Path=/v2/**
          filters:
            - "MessageService"
            - RewritePath=/v2(?<segment>/?.*), /v1$\{segment}
        - id: v1
          uri: https://api-xfb.easipay.net/v1
          predicates:
            - Path=/v1/**
          filters:
            - "Sign"
            - RewritePath=/v1(?<segment>/?.*), /v1$\{segment}
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      username: dev
      password: dev.com
      database: pay
      authentication-database: pay

logging:
  level:
    org:
      springframework: error
    tech:
      aomi: debug
  pattern:
    console: "%clr(%d){blue} [%clr(%-5level){lightgreen}] [%logger{0}] - %msg%n"
    file: "%d [%-5level] [%logger{0}] - %msg%n"

